### PR TITLE
solved mrcll

### PR DESCRIPTION
**Pull request by remrcll**
pls check

### CODE REVIEW

**Comment by Ungoot** [comment]
`:not(td) {
    background-color: white;
}`

This is not doing anything as the default background color is already white.

Also on line 5 and 9 you are repeating yourself. You can combine line 5, 9 and the `:not` selector to make it more tidy. You want to select the second and third child, in other words not the first child.

Please try it like that.

**Comment by remrcll** [comment]
> `:not(td) { background-color: white; }`
> 
> This is not doing anything as the default background color is already white.
> 
> Also on line 5 and 9 you are repeating yourself. You can combine line 5, 9 and the `:not` selector to make it more tidy. You want to select the second and third child, in other words not the first child.
> 
> Please try it like that.

I know all that,  I could've done it even without :not selector, but the exercise is written in a stupid way and it's explicitly asking:

> Look at the mock-up file and create the table shown using the :first-child, :last-child, :nth-child and :not pseudo classes.

If I don't do exactly as the .md file says, or the result is not looking always exactly the same as the mock-up shows, then you never approve. Now I did exactly as the exercise was asking, and it looks exactly as the mock-up looks like, and now that is the problem. I really don't get what I should follow anymore. Maybe somebody should revise these exercises, so they would be more clear. 80% of them are asking something completely unlogic, or they are not clear at all.

**Comment by Ungoot** [comment]
Ok show me how you would do it. Forget about the exercise, show me your way.

**Comment by Ungoot** [comment]
Works, good job

**Pull request merged**
